name: CI
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "cy:percy"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
